name: test

on:
  push:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/cache.txt'
          key: npm-packages-${{ hashFiles('**/a.txt') }}

      - run: |
          cat bbb/ccc/cache.txt